### ISSUE TITLE
JsonSchema IsValid Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by oscarcabrero** [JamesNK/Newtonsoft.Json.Schema#154]
IsValid throws when passed some jobjects containing properties/jtokens
with Type =string
and Value= null

schema property:
  "EmailCcList": {
      "description": "The email addresses ",
      "type": "string"
    }

```
entityJObject,Add("EmailCcList", new JValue((string)null);
entityJObject.IsValid(operationSchema, out errors)
```
at Newtonsoft.Json.Schema.Infrastructure.Validation.PrimativeScope.EvaluateTokenCore(JsonToken token, Object value, Int32 depth)
  at Newtonsoft.Json.Schema.Infrastructure.Validation.SchemaScope.CreateScopesAndEvaluateToken(JsonToken token, Object value, Int32 depth, JSchema schema, SchemaScope parent, ContextBase context)
  at Newtonsoft.Json.Schema.Infrastructure.Validation.ObjectScope.EvaluateTokenCore(JsonToken token, Object value, Int32 depth)
  at Newtonsoft.Json.Schema.Infrastructure.Validation.Validator.ValidateCurrentToken(JsonToken token, Object value, Int32 depth)
  at Newtonsoft.Json.Schema.JSchemaValidatingReader.ValidateCurrentToken()
  at Newtonsoft.Json.Schema.SchemaExtensions.Validate(JToken source, JSchema schema, SchemaValidationEventHandler validationEventHandler)
  at Newtonsoft.Json.Schema.SchemaExtensions.IsValid(JToken source, JSchema schema, IList`1& errors)
```

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/c3355192d386ac7ecdd6cd0e50c725e0d9292e03
