### ISSUE TITLE
IReadOnlyDictionary not recognized as a Dictionary

### ISSUE THREAD

**Issue by syncro-bpierpont** [JamesNK/Newtonsoft.Json.Schema#184]
Newtonsoft.Json will successfully deserialize a Dictionary into an IReadOnlyDictionary.
However, Newtonsoft.Json.Schema reports that IReadOnlyDictionary is not a Dictionary and therefore the assignment is not possible.

**Comment by FLAMESpl** [comment]
Hi, any update on this? I also faced this issue.

```
System.Exception: 'Type System.Collections.Generic.IReadOnlyDictionary`2[System.Guid,System.Int32] is not a dictionary.'
  at Newtonsoft.Json.Schema.Infrastructure.ReflectionUtils.GetDictionaryKeyValueTypes(Type dictionaryType, Type& keyType, Type& valueType)
   at Newtonsoft.Json.Schema.Generation.JSchemaGeneratorInternal.PopulateSchema(JSchema schema, JsonContract contract, JsonProperty memberProperty, Required valueRequired)
   at Newtonsoft.Json.Schema.Generation.JSchemaGeneratorInternal.GenerateInternal(Type type, Nullable`1 valueRequired, JsonProperty memberProperty, JsonContainerContract container, JSchemaGenerationProvider currentGenerationProvider)
   at Newtonsoft.Json.Schema.Generation.JSchemaGeneratorInternal.GenerateObjectSchema(JSchema schema, Type type, JsonObjectContract contract)
   at Newtonsoft.Json.Schema.Generation.JSchemaGeneratorInternal.PopulateSchema(JSchema schema, JsonContract contract, JsonProperty memberProperty, Required valueRequired)
   at Newtonsoft.Json.Schema.Generation.JSchemaGeneratorInternal.GenerateInternal(Type type, Nullable`1 valueRequired, JsonProperty memberProperty, JsonContainerContract container, JSchemaGenerationProvider currentGenerationProvider)
   at Newtonsoft.Json.Schema.Generation.JSchemaGeneratorInternal.Generate(Type type, Required required)
```

**Comment by marekott** [comment]
Hi, any plans for release with that fix? We have also encountered that bug and it is critical for us.

**Comment by marekott** [comment]
Hi @JamesNK, any chance for that release? This is really important for us.

**Comment by JamesNK** [comment]
There will be a new release in 1-2 weeks.

Until then you can use a pre-release package from MyGet - https://www.myget.org/feed/json-net/package/nuget/Newtonsoft.Json.Schema

**Comment by marekott** [comment]
Hi @JamesNK, any chance for that full release?

**Comment by JamesNK** [comment]
Beta is on NuGet - https://www.nuget.org/packages/Newtonsoft.Json.Schema/3.0.14-beta3

**Comment by marekott** [comment]
Thanks @JamesNK, it is solving my problem. However I cannot use beta version on production. What is a planned date for stable release?

**Comment by JamesNK** [comment]
Non-preview release - https://www.nuget.org/packages/Newtonsoft.Json.Schema/3.0.14

**Comment by rajatshuvro** [comment]
Hi @JamesNK ,
I am using 3.0.15 and facing the same error. Any recommendations:

Unhandled exception. System.Exception: Type Ilmn.Das.Std.AppUtils.Collections.ReadOnlyOrderedDictionary.IReadOnlyOrderedDictionary`1[***.JsonSample] is not a dictionary.
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetDictionaryKeyValueTypes(Type dictionaryType, Type& keyType, Type& valueType)
   at Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal(Type type, Required valueRequired, Boolean required)
   at Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateObjectSchema(Type type, JsonObjectContract contract)
   at Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal(Type type, Required valueRequired, Boolean required)
   at Newtonsoft.Json.Schema.JsonSchemaGenerator.Generate(Type type, JsonSchemaResolver resolver, Boolean rootSchemaNullable)
   at Newtonsoft.Json.Schema.JsonSchemaGenerator.Generate(Type type)
