### ISSUE TITLE
JSchemaUrlResolver fails with root level $ref

### ISSUE THREAD

**Issue by safepage** [JamesNK/Newtonsoft.Json.Schema#195]
Hi,

Given the following JSON Schema:

**A.json:**
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "a": {
            "type": "array",
            "items": {
                "$ref": "./B.json"
            }
        }
    }
}
```

**B.json:**
```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref": "./C.json"
}
```

**C.json**
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"p": {
			"type": "string"
		}
	},
	"additionalProperties": false
}
```

**The example reader code fails:**
```cs
using (StreamReader file = File.OpenText(@"C:\Temp\JsonTest\A.json"))
using (JsonTextReader reader = new JsonTextReader(file))
{
    JSchemaUrlResolver resolver = new JSchemaUrlResolver();
    JSchema schema = JSchema.Load(reader, new JSchemaReaderSettings
    {
        Resolver = resolver,
        BaseUri = new Uri(@"C:\Temp\JsonTest\A.json")
    });
}
```

**With the exception:**

```
Newtonsoft.Json.Schema.JSchemaReaderException
  HResult=0x80131500
  Message=Could not resolve schema reference './B.json'. Path 'properties.a.items', line 8, position 22.
  Source=Newtonsoft.Json.Schema
  StackTrace:
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchemas()
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ReadRoot(JsonReader reader, Boolean resolveDeferedSchemas)
   at Newtonsoft.Json.Schema.JSchema.Load(JsonReader reader, JSchemaReaderSettings settings)
   at ConsoleApp1.Program.Main(String[] args) in c:\temp\ConsoleApp1\Program.cs:line 21
```

**Comment by JamesNK** [comment]
Fixed. The issue is B.json. Referenced schemas that contain a $ref in the root JSON object have a bug. Until a new version is released you can avoid this issue by modifying your schemas to not have root $ref.
