### ISSUE TITLE
Null JSchema, JSchemaConverter and NullValueHandling.Include

### ISSUE THREAD

**Issue by jbockle** [JamesNK/Newtonsoft.Json.Schema#228]
when a reference to a JSchema is null, and using NullValueHandling.Include, a deserialization error is encountered.  This is probably due to the JSchemaConverter not checking if the value is null token type before passing it to JSchema.Load.

example: https://dotnetfiddle.net/xpWD9C

```
Newtonsoft.Json.Schema.JSchemaReaderException: Unexpected token encountered when reading schema. Expected StartObject, Boolean, got Null. Path 'Schema', line 2, position 16.
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.EnsureToken(JsonReader reader, String name, List`1 tokenTypes, String errorMessage)
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ValidateSchemaStart(JsonReader reader, String name)
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ReadRoot(JsonReader reader, Boolean resolveDeferedSchemas)
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ReadRoot(JsonReader reader)
   at Newtonsoft.Json.Schema.JSchema.Load(JsonReader reader, JSchemaReaderSettings settings)
   at Newtonsoft.Json.Schema.JSchema.Load(JsonReader reader)
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Program.Main()
```

**Comment by JamesNK** [comment]
Thanks for reporting the issue. Fixed.
