### ISSUE TITLE
Json.NET Schema fails on RHEL 9 when registering license

### ISSUE THREAD

**Issue by Meddington** [JamesNK/Newtonsoft.Json.Schema#345]
RedHat Enterprise Linux v9 has removed support for SHA1 signatures. When starting up a program that uses Netonsoft.Json.Schema, the program exceptions in `CryptographyHelpers.ValidateData`.

This can be worked around by changing the base OS cryptographic settings, but not if the OS is running in FIPS mode. For FIPS mode no workaround has been found yet.

```
Unhandled exception. Interop+Crypto+OpenSslCryptographicException: error:020000AD:rsa routines::invalid key length
   at Interop.Crypto.DecodeSubjectPublicKeyInfo(ReadOnlySpan`1 source, EvpAlgorithmId algorithmId)
   at System.Security.Cryptography.RSAImplementation.RSAOpenSsl.ImportParameters(RSAParameters parameters)
   at Newtonsoft.Json.Schema.Infrastructure.Licensing.CryptographyHelpers.ValidateData(Byte[] data, Byte[] signature)
   at Newtonsoft.Json.Schema.Infrastructure.Licensing.LicenseHelpers.ReadLicenseData(DateTime releaseDate, String licenseBase64, Int32 licenseId)
   at Newtonsoft.Json.Schema.Infrastructure.Licensing.LicenseHelpers.RegisterLicense(String license, DateTime releaseDate)
   at Newtonsoft.Json.Schema.Infrastructure.Licensing.LicenseHelpers.RegisterLicense(String license)
   at Newtonsoft.Json.Schema.License.RegisterLicense(String license)
   at XXXX.XXXX.JsonSchemaInitializer.RegisterNewtonsoftJsonSchemaLicense() in XXXXX/XXXX/Startup.cs:line 318
```

**Comment by JamesNK** [comment]
Fixed in https://www.nuget.org/packages/Newtonsoft.Json.Schema/4.0.1-beta1
