### ISSUE TITLE
PlatformNotSupportedException on Ubuntu

### ISSUE THREAD

**Issue by meichtf** [JamesNK/Newtonsoft.Json.Schema#46]
I get the following exception when I want to register a license on Ubuntu:

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Newtonsoft.Json.Schema.Infrastructure.Licensing.CryptographyHelpers.ValidateData(Byte[] data, Byte[] signature)
   at Newtonsoft.Json.Schema.Infrastructure.Licensing.LicenseHelpers.RegisterLicense(String license, DateTime releaseDate)
   at Newtonsoft.Json.Schema.Infrastructure.Licensing.LicenseHelpers.RegisterLicense(String license)
   at Autodesk.Forge.Dm.Server.Startup.ConfigureServices(IServiceCollection services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

**Comment by JamesNK** [comment]
Hi

I believe this issue you are having was previously fixed but wasn't yet released. 2.0.5 has just been released which includes the fix.

Could you try updating Newtonsoft.Json.Schema and see whether that fixes the error you are getting.

**Comment by meichtf** [comment]
Hi


Thanks for your quick answer. I will try it on Monday and report back.


Freddy

________________________________

**Comment by meichtf** [comment]
Version 2.0.5 fixes the issue. Thank you

**Comment by JamesNK** [comment]
Fantastic. I was confident but not certain :)
