### ISSUE TITLE
Resolving referenced schema on local filesystem fails if the BaseUri contains whitespaces

### ISSUE THREAD

**Issue by swifmaneum** [JamesNK/Newtonsoft.Json.Schema#49]
I'm trying to resolve a referenced schema on my local filesystem like described in the [documentation](http://www.newtonsoft.com/jsonschema/help/html/LoadingSchemas.htm):

```
string schemapath = @"C:\Users\myusername\Desktop\Test\contacts.schema.json";

using (StreamReader file = File.OpenText(schemapath))
using (JsonTextReader reader = new JsonTextReader(file))
{
    JSchemaUrlResolver resolver = new JSchemaUrlResolver();

    JSchema schema = JSchema.Load(reader, new JSchemaReaderSettings
    {
        Resolver = resolver,                   
        BaseUri = new Uri(schemapath)
     });
}
```

This works fine as long as the `schemapath` does not contain any whitespaces. Placing the schemas in a folder containing whitespaces like so `string schemapath = @"C:\Users\myusername\Desktop\Test with whitespace\contacts.schema.json";` leads to the following exception:

```
Newtonsoft.Json.Schema.JSchemaReaderException was unhandled by user code
  HResult=-2146233088
  LineNumber=4
  LinePosition=12
  Message=Error when resolving schema reference 'contact.schema.json'. Path 'items', line 4, position 12.
  Path=items
  Source=Newtonsoft.Json.Schema
  StackTrace:
       at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchema(DeferedSchema deferedSchema)
       at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchemas()
       at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ReadRoot(JsonReader reader, Boolean resolveDeferedSchemas)
       at Newtonsoft.Json.Schema.JSchema.Load(JsonReader reader, JSchemaReaderSettings settings)
       at JsonNetSchemaTest.SchemaGeneratorTest.TestCreateWithWhitespace() in ...
  InnerException: 
       HResult=-2147024893
       Message=Could not find a part of the path 'C:\Users\myusername\Desktop\Test%20with%20whitespace\contact.schema.json'.
       Source=mscorlib
       StackTrace:
            at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
            at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
            at Newtonsoft.Json.Schema.Infrastructure.WebRequestDownloader.GetStream(Uri uri, ICredentials credentials, Nullable`1 timeout, Nullable`1 byteLimit)
            at Newtonsoft.Json.Schema.JSchemaUrlResolver.GetSchemaResource(ResolveSchemaContext context, SchemaReference reference)
            at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolvedSchema(Uri schemaId, Uri resolvedSchemaId)
            at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchema(DeferedSchema deferedSchema)
       InnerException: 
```

The schemas I used are pretty basic: 

> contacts.schema.json

```
{
  "title": "Contact list",
  "type": "array",
  "items": {
    "$ref": "contact.schema.json"
  }
}
```

> contact.schema.json

```
{
  "title": "Contact information",
  "type": "object",
  "properties": {
    "FirstName": {
      "title": "First name",
      "type": "string"
    },
    "FamilyName": {
      "title": "Family name",
      "type": "string"
    }
  },
  "required": [
    "FirstName",
    "FamilyName"
  ]
}
```

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/6cabf2f0769bda3253d2f8cfb0ad749e854a5b02

This will be in the next version. I'll post here when it is on NuGet.

**Comment by JamesNK** [comment]
Now available - https://www.nuget.org/packages/Newtonsoft.Json.Schema/2.0.7
