### ISSUE TITLE
MultipleOf overflow error

### ISSUE THREAD

**Issue by JamesNK** [JamesNK/Newtonsoft.Json.Schema#68]
```
at System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
at System.Decimal.Remainder(Decimal d1, Decimal d2)
at Newtonsoft.Json.Schema.Infrastructure.MathHelpers.IsIntegerMultiple(Object integer, Decimal multipleOf)
at Newtonsoft.Json.Schema.Infrastructure.MathHelpers.IsIntegerMultiple(Object integer, Double multipleOf)
at Newtonsoft.Json.Schema.Infrastructure.Validation.PrimativeScope.ValidateInteger(JSchema schema, Object value)
at Newtonsoft.Json.Schema.Infrastructure.Validation.PrimativeScope.EvaluateTokenCore(JsonToken token, Object value, Int32 depth)
at Newtonsoft.Json.Schema.Infrastructure.Validation.SchemaScope.CreateScopesAndEvaluateToken(JsonToken token, Object value, Int32 depth, JSchema schema)
at Newtonsoft.Json.Schema.Infrastructure.Validation.ObjectScope.EvaluateTokenCore(JsonToken token, Object value, Int32 depth)
at Newtonsoft.Json.Schema.Infrastructure.Validation.Validator.ValidateCurrentToken(JsonToken token, Object value, Int32 depth)
at Newtonsoft.Json.Schema.JSchemaValidatingReader.ValidateCurrentToken()
at Newtonsoft.Json.Schema.JSchemaValidatingReader.Read()
at Newtonsoft.Web.Controllers.Api.JsonSchemaController.ValidateSchema(ValidateResponse response, ValidateRequest request, JSchema schema, List`1 schemaErrors)
at Newtonsoft.Web.Controllers.Api.JsonSchemaController.<>c__DisplayClass4_1.<Valiate>b__0()
at Newtonsoft.Web.Infrastructure.HardAborter.<>c__DisplayClass5_0`1.<Start>b__0()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at Newtonsoft.Web.Controllers.Api.JsonSchemaController.<Valiate>d__4.MoveNext()
```

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json.Schema/commit/89c11ba681f472b9227fe9ccb707b02f9edfedc1
