### ISSUE TITLE
A package.json was not found at C:\Users\sub-user\package.json how can i install package.json

### ISSUE THREAD

**Issue by almoharebh** [JamesNK/Newtonsoft.Json.Schema#89]
C:\Users\sub-user>npm-check
A package.json was not found at C:\Users\sub-user\package.json
For more detail, add `--debug` to the command

C:\Users\sub-user>npm-check --debug
[npm-check] debug
cli.flags { update: false,
  u: false,
  global: false,
  g: false,
  skipUnused: false,
  s: false,
  production: false,
  p: false,
  saveExact: false,
  E: false,
  color: false,
  emoji: true,
  spinner: true,
  debug: true,
  dir: 'C:\\Users\\sub-user' }
===============================
[npm-check] debug
cli.input []
===============================
[npm-check] debug
set key spinner to value true
===============================
[npm-check] debug
set key ignore to value undefined
===============================
[npm-check] debug
set key cwdPackageJson to value { devDependencies: {},
  dependencies: {},
  error:
   Error: A package.json was not found at C:\Users\sub-user\package.json
       at readPackageJson (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\in\read-package-json.js:12:21)
       at Promise (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\state\init.js:19:25)
       at init (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\state\init.js:10:12)
       at state (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\state\state.js:73:12)
       at init (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\index.js:7:12)
       at Object.<anonymous> (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\cli.js:89:1)
       at Module._compile (module.js:570:32)
       at Object.Module._extensions..js (module.js:579:10)
       at Module.load (module.js:487:32)
       at tryModuleLoad (module.js:446:12) }
===============================
[npm-check] debug
set key cwd to value C:\Users\sub-user
===============================
[npm-check] debug
set key nodeModulesPath to value C:\Users\sub-user\node_modules
===============================
A package.json was not found at C:\Users\sub-user\package.json
    7 |    let error;
    8 |    try {
    9 |        pkg = require(filename);
   10 |    } catch (e) {
   11 |        if (e.code === 'MODULE_NOT_FOUND') {
 > 12 |            error = new Error(`A package.json was not found at ${filename}`);
   13 |        } else {
   14 |            error = new Error(`A package.json was found at ${filename}, but it is not valid.`);
   15 |        }
   16 |    }
   17 |    return merge(pkg, {devDependencies: {}, dependencies: {}, error: error});

   at readPackageJson (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\in\read-package-json.js:12:21)
   at Promise (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\state\init.js:19:25)
   at init (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\state\init.js:10:12)
   at state (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\state\state.js:73:12)
   at init (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\index.js:7:12)
   at Object.<anonymous> (C:\Users\sub-user\AppData\Roaming\npm\node_modules\npm-check\lib\cli.js:89:1)
   at Module._compile (module.js:570:32)
   at Object.Module._extensions..js (module.js:579:10)
   at Module.load (module.js:487:32)
   at tryModuleLoad (module.js:446:12)

**Comment by JamesNK** [comment]
http://dish.allrecipes.com/baking-cheesecake-step-by-step/
